name: Release kokoro-tts

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like v1.0.0, v2.1.3, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to create a GitHub Release

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y espeak-ng patchelf

    - name: Install Python dependencies
      working-directory: kokoro
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade phonemizer-fork
        pip install nuitka

    - name: Determine site-packages path
      id: site_packages
      run: |
        SITE_PACKAGES=$(python -c "import site; print(site.getsitepackages()[0])")
        echo "site_packages=$SITE_PACKAGES" >> $GITHUB_OUTPUT

    - name: Build binary with Nuitka
      working-directory: kokoro
      run: |
        SITE_PACKAGES="${{ steps.site_packages.outputs.site_packages }}"
        python -m nuitka --onefile \
          --output-dir=src \
          --include-data-files="$SITE_PACKAGES/kokoro_onnx/config.json"=kokoro_onnx/config.json \
          --include-data-files="$SITE_PACKAGES/language_tags/data/json/index.json"=language_tags/data/json/index.json \
          --include-data-files="$SITE_PACKAGES/language_tags/data/json/registry.json"=language_tags/data/json/registry.json \
          --include-data-dir="$SITE_PACKAGES/espeakng_loader/espeak-ng-data"=espeakng_loader/espeak-ng-data \
          --include-data-files="$SITE_PACKAGES/espeakng_loader/libespeak-ng.so"=espeakng_loader/libespeak-ng.so \
          --include-distribution-metadata=kokoro-onnx \
          --lto=yes \
          --python-flag=no_site \
          src/kokoro-tts.py

    - name: Create GitHub Release and upload binary
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        files: kokoro/src/kokoro-tts.bin
